package com.example.ch_users_e2e_sandbox;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class PersistenceVerificationIntegrationTest {

    @LocalServerPort
    private int port;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Test
    void shouldExposeH2Console() throws IOException, InterruptedException {
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create("http://localhost:" + port + "/h2-console/"))
                .GET()
                .build();

        HttpResponse<String> response = HttpClient.newHttpClient()
                .send(request, HttpResponse.BodyHandlers.ofString());

        assertThat(response.statusCode()).isEqualTo(200);
        assertThat(response.body()).contains("H2 Console");
    }

    @Test
    void shouldCreateUsersTableWithExpectedColumnsAndConstraints() {
        List<Map<String, Object>> tables = jdbcTemplate.queryForList("SHOW TABLES");

        assertThat(tables)
                .anySatisfy(table -> assertThat(table.values()).contains("USERS"));

        List<Map<String, Object>> columns = jdbcTemplate.queryForList("""
                SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
                FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_NAME = 'USERS'
                """);

        Map<String, Map<String, Object>> columnsByName = columns.stream()
                .collect(Collectors.toMap(
                        column -> column.get("COLUMN_NAME").toString(),
                        Function.identity()));

        assertThat(columnsByName).containsKeys("ID", "NAME", "EMAIL", "MEMBERSHIP_TYPE", "CREATED_AT");
        assertThat(columnsByName.get("ID").get("DATA_TYPE").toString()).isEqualTo("BIGINT");
        assertThat(columnsByName.get("NAME").get("IS_NULLABLE").toString()).isEqualTo("NO");
        assertThat(columnsByName.get("EMAIL").get("IS_NULLABLE").toString()).isEqualTo("NO");
        assertThat(columnsByName.get("MEMBERSHIP_TYPE").get("IS_NULLABLE").toString()).isEqualTo("NO");
        assertThat(columnsByName.get("CREATED_AT").get("IS_NULLABLE").toString()).isEqualTo("NO");

        List<Map<String, Object>> constraints = jdbcTemplate.queryForList("""
                SELECT CONSTRAINT_TYPE
                FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
                WHERE TABLE_NAME = 'USERS'
                """);

        List<String> constraintTypes = constraints.stream()
                .map(constraint -> constraint.get("CONSTRAINT_TYPE").toString())
                .toList();

        assertThat(constraintTypes).contains("PRIMARY KEY", "UNIQUE");
    }

    @Test
    void shouldPersistManualInsertWithAutoGeneratedId() {
        jdbcTemplate.update("DELETE FROM USERS WHERE EMAIL = ?", "test@example.com");

        int insertedRows = jdbcTemplate.update("""
                INSERT INTO USERS (NAME, EMAIL, MEMBERSHIP_TYPE, CREATED_AT)
                VALUES ('Test User', 'test@example.com', 'standard', NOW())
                """);

        assertThat(insertedRows).isEqualTo(1);

        Map<String, Object> persistedUser = jdbcTemplate.queryForMap("""
                SELECT ID, NAME, EMAIL, MEMBERSHIP_TYPE, CREATED_AT
                FROM USERS
                WHERE EMAIL = 'test@example.com'
                """);

        assertThat(persistedUser.get("ID")).isNotNull();
        assertThat(persistedUser.get("NAME")).isEqualTo("Test User");
        assertThat(persistedUser.get("EMAIL")).isEqualTo("test@example.com");
        assertThat(persistedUser.get("MEMBERSHIP_TYPE")).isEqualTo("standard");
        assertThat(persistedUser.get("CREATED_AT")).isNotNull();
    }
}
